<div id="navigation" align="center">
	<ul>
		<li><a href="index.php">HOME</a></li>
		<li><a href="aboutus.php">ABOUT US</a></li>
		<li><a href="contactus.php">CONTACT US</a></li>
		<li><a href="exception_list.php">EXCEPTION LIST</a></li>
		<li><a href="cms/admin/index.php">ADMIN</a></li>
		<li><a href="https://studentportal.utp-prism.my/studentportal/StudentLogin.aspx">PRISM</a></li>
		<li><a href="http://utptt.utp.edu.my/">UTP TIMETABLE CENTER</a></li>
	</ul>
</div>